### ISSUE TITLE
Watch screen blacks out

### ISSUE THREAD

**Issue by davozed** [xmile1/fitbit-anylist#1]
Thank you for your list app for Fitbit.

It's a considerable improvement over anything else that is available.

I am having a recurring issue with my watch screen blacking out. The screen is pitch black except for the checkboxes which are in white.

I have tried to synching my phone and watch and restarting both the phone and the watch and there is no change.

I can get the screen back if I go down to the very bottom of the settings and change the screen color to another color. Any color.

Thanks.

Dave

**Comment by davozed** [comment]
I have tried repeatedly to clip a photo of the watch screen blacked out with the white tick boxes but I can't seem to do it.

There is a function for that here but it doesn't seem to work. At least not for me.

**Comment by xmile1** [comment]
Hi @davozed
 
Maybe you can take a photo/video using your mobile phone as i am unable to reproduce the issue here so i am hoping that i might get a hint from seeing some visuals.

**Comment by davozed** [comment]
Thank you for your reply.

Here is a screenshot of what my watch screen looks like when it's blacked out. I tried to send it to you over GitHub but I wasn't able to get the system to accept the photo.

I've worked out what the problem is. When I have too many items on a list, when I exceed the maximum number of items, the problem occurs.

When I have too many items on the list on the phone, only the first 33 (?) show up on the watch. But also, it begins to black out the screen. The minute that I reduce the number of items on the phone, the blacking out disappears.

So that's the solution to the problem. In your FAQs, you may want to add that as something that people can watch out for.

A few more suggestions for the app:

1. The buttons at the top of the lists are difficult (for me) to engage with any certainty. The one that takes a person back to the menu of lists and the one that resets the list by removing all of the check marks.

I don't know what can be done here but making the target areas bigger and more responsive would help me.

2. Making changes on the phone list can sometimes uncheck the items on the watch list.

3. More and brighter colors for the watch screen would help me.  I like to freshen up my apps from time to time, to keep my interest in them up.

Thanks again for the great app and thank you for your help.

Dave Cunningham
Calgary CANADA
403-571-7171

Aug 5, 2023 12:27:45 a.m. Uyiosa Enabulele ***@***.***>:

**Comment by xmile1** [comment]
Hi @davozed, thanks for your detailed response and suggestions. I will refactor the buttons at the top when I have some time, add a message to the FAQ as you suggested, and look into the bug.

Regarding the colors, I will see what new colors we can add, you can also suggest some combinations if you want and even add a pull request here if you feel up to it. https://github.com/xmile1/fitbit-mylist/blob/08cd3798f1a14a7ac89abda0e7900bc62285d6b6/app/utils/setColorScheme.js#L3-L60
